--These Queries were written for Geri Hegstad and are to be run on the Labs database.
--The first query finds all accessions which do not have a contact designated to receive a report.
--The second finds accessions which have only one contact designated to receive a report, but no correspondence type listed for that contact.
--The date of last modification for these queries is 8/26/2015.
SELECT ACCESSION_ID, ACCESSION_ID2, ACCESSION_NO, STATUS_CODE, FINALIZED_DATE FROM 
 
(SELECT DISTINCT ACCESSION_ID FROM UVIS_DL_ACC_CONTACTS WHERE RR_ACC_YN = 'N') 
 
INNER JOIN (SELECT ACCESSION_ID AS ACCESSION_ID3, ACCESSION_NO, STATUS_CODE, FINALIZED_DATE FROM UVIS_DL_ACCESSIONS WHERE STATUS_CODE = 'F' AND FINALIZED_DATE BETWEEN '01-AUG-14' AND '24-AUG-15' AND ACCESSION_NO NOT LIKE '%-%') ON ACCESSION_ID = ACCESSION_ID3 
 
LEFT OUTER JOIN (SELECT DISTINCT ACCESSION_ID AS ACCESSION_ID2 FROM UVIS_DL_ACC_CONTACTS WHERE RR_ACC_YN = 'Y') ON ACCESSION_ID = ACCESSION_ID2 WHERE ACCESSION_ID2 is NULL;

--
SELECT * FROM

(SELECT COUNT(ACCESSION_ID) AS NUM_YES, ACCESSION_ID FROM UVIS_DL_ACC_CONTACTS WHERE RR_ACC_YN = 'Y' GROUP BY ACCESSION_ID)

INNER JOIN (SELECT DISTINCT ACCESSION_ID AS ACCESSION_ID2 FROM UVIS_DL_ACC_CONTACTS WHERE RR_ACC_YN = 'Y' AND RR_CORRESPONDENCE = 'N') ON ACCESSION_ID = ACCESSION_ID2 WHERE NUM_YES = '1';