--Finds dlab billing adjustments (960-1701 product codes).

SELECT CLIENT_ID, ACCESSION_NO, CLIENT, CHARGE_AMT, ADJ_REASON, COMMENTS, D_TSID_DATE, LUN FROM 

(SELECT eod.CLIENT_ID, eod.ACCESSION_ID, NVL(client.BUSINESS_FARM_NAME, client.LAST_NAME||','||client.FIRST_NAME) client, eod.CHARGE_AMT, eod.ADJ_REASON, eod.COMMENTS, eod_stat.D_TSID_DATE, eod.LUN 

FROM UVIS_DL_EOD_CHARGES eod, UVIS_DL_EOD_STATUS eod_stat, UVIS_CLIENT client

WHERE eod.PRODUCT_LINE_ID = '960' AND eod.PRODUCT_SEQ_ID = '1701' AND eod.D_TSID = eod_stat.D_TSID AND eod_stat.D_TSID_DATE BETWEEN :p_start_date and :p_end_date AND eod.CLIENT_ID = client.CLIENT_ID)

LEFT JOIN (SELECT ACCESSION_NO, ACCESSION_ID AS ACCESSION_ID2 FROM UVIS_DL_ACCESSIONS) ON ACCESSION_ID = ACCESSION_ID2

ORDER BY CLIENT_ID;