--This query finds instances of a patient that was diagnosed with arthritis (this includes a few different diagnosis IDs) and returns vital signs and any product codes
--that showed up on a bill other than 800-700.
SELECT UVIS_PATIENT.PATIENT_ID, UVIS_PATIENT.PATIENT_NAME, UVIS_CLIENT.LAST_NAME, UVIS_CLIENT.FIRST_NAME, UVIS_PRIMARY_DIAGNOSIS_M.DIAGNOSIS, UVIS_MR_EPISODE.EPISODE_ID, UVIS_MR_REQUEST.REQUEST_ID, UVIS_MR_REQUEST.STATUS, UVIS_PATIENT.BIRTHDATE, UVIS_MR_REQUEST.ENTERED_DATE_TIME, UVIS_MR_REQUEST_ITEMS.PRODUCT_LINE_ID, UVIS_MR_REQUEST_ITEMS.PRODUCT_SEQ_ID, UVIS_PRODUCT.LONG_DESCRIPTION,
UVIS_MR_VITAL_SIGNS.TEMP, UVIS_MR_VITAL_SIGNS.WEIGHT, UVIS_MR_VITAL_SIGNS.BODY_CONDITION 

FROM UVIS_PATIENT, UVIS_CLIENT, UVIS_PRIMARY_DIAGNOSIS_M, UVIS_MR_DIAGNOSIS, UVIS_MR_EPISODE, UVIS_MR_REQUEST, UVIS_MR_REQUEST_ITEMS, UVIS_MR_VITAL_SIGNS, UVIS_PRODUCT

WHERE UVIS_PATIENT.CLIENT_ID = UVIS_CLIENT.CLIENT_ID AND UVIS_MR_EPISODE.PATIENT_ID = UVIS_PATIENT.PATIENT_ID AND UVIS_MR_DIAGNOSIS.EPISODE_ID = UVIS_MR_EPISODE.EPISODE_ID AND UVIS_MR_DIAGNOSIS.DIAGNOSIS_ID = UVIS_PRIMARY_DIAGNOSIS_M.DIAGNOSIS_ID 
AND (UVIS_MR_DIAGNOSIS.DIAGNOSIS_ID = 2535 OR UVIS_MR_DIAGNOSIS.DIAGNOSIS_ID = 214 OR UVIS_MR_DIAGNOSIS.DIAGNOSIS_ID = 213 OR UVIS_MR_DIAGNOSIS.DIAGNOSIS_ID = 211 OR UVIS_MR_DIAGNOSIS.DIAGNOSIS_ID = 2537)
AND UVIS_PATIENT.SPECIES_ID = 6 AND UVIS_MR_REQUEST.EPISODE_ID = UVIS_MR_EPISODE.EPISODE_ID AND UVIS_MR_REQUEST_ITEMS.REQUEST_ID = UVIS_MR_REQUEST.REQUEST_ID AND UVIS_MR_VITAL_SIGNS.EPISODE_ID = UVIS_MR_EPISODE.EPISODE_ID AND UVIS_PRODUCT.PRODUCT_LINE_ID = UVIS_MR_REQUEST_ITEMS.PRODUCT_LINE_ID
AND UVIS_PRODUCT.PRODUCT_SEQ_ID = UVIS_MR_REQUEST_ITEMS.PRODUCT_SEQ_ID AND UVIS_MR_REQUEST_ITEMS.PRODUCT_LINE_ID != 800 AND UVIS_MR_REQUEST_ITEMS.PRODUCT_SEQ_ID != 700 AND UVIS_MR_VITAL_SIGNS.VITALS_DATETIME = (SELECT MIN(UVIS_MR_VITAL_SIGNS.VITALS_DATETIME) FROM UVIS_MR_VITAL_SIGNS WHERE UVIS_MR_VITAL_SIGNS.EPISODE_ID = UVIS_MR_EPISODE.EPISODE_ID);


--This is the same query as above except it only shows 800-700's and it queries the lab side for Results of the test.
SELECT UVIS_PATIENT.PATIENT_ID, UVIS_PATIENT.PATIENT_NAME, UVIS_CLIENT.LAST_NAME, UVIS_CLIENT.FIRST_NAME, UVIS_PRIMARY_DIAGNOSIS_M.DIAGNOSIS, UVIS_MR_EPISODE.EPISODE_ID, UVIS_MR_REQUEST.REQUEST_ID, UVIS_MR_REQUEST.STATUS, UVIS_PATIENT.BIRTHDATE, UVIS_MR_REQUEST.ENTERED_DATE_TIME, UVIS_MR_REQUEST_ITEMS.PRODUCT_LINE_ID, UVIS_MR_REQUEST_ITEMS.PRODUCT_SEQ_ID, UVIS_PRODUCT.LONG_DESCRIPTION,
UVIS_MR_VITAL_SIGNS.TEMP, UVIS_MR_VITAL_SIGNS.WEIGHT, UVIS_MR_VITAL_SIGNS.BODY_CONDITION, UVIS_CL_TEST_M.SHORT_NAME, UVIS_CL_RESULT.RESULT_VALUE

FROM UVIS_CL_TEST_M, UVIS_CL_REQUEST, UVIS_CL_RESULT, UVIS_PATIENT, UVIS_CLIENT, UVIS_PRIMARY_DIAGNOSIS_M, UVIS_MR_DIAGNOSIS, UVIS_MR_EPISODE, UVIS_MR_REQUEST, UVIS_MR_REQUEST_ITEMS, UVIS_MR_VITAL_SIGNS, UVIS_PRODUCT

WHERE UVIS_PATIENT.CLIENT_ID = UVIS_CLIENT.CLIENT_ID AND UVIS_MR_EPISODE.PATIENT_ID = UVIS_PATIENT.PATIENT_ID AND UVIS_MR_EPISODE.PATIENT_ID = UVIS_PATIENT.PATIENT_ID AND UVIS_MR_DIAGNOSIS.EPISODE_ID = UVIS_MR_EPISODE.EPISODE_ID AND UVIS_MR_DIAGNOSIS.DIAGNOSIS_ID = UVIS_PRIMARY_DIAGNOSIS_M.DIAGNOSIS_ID 
AND (UVIS_MR_DIAGNOSIS.DIAGNOSIS_ID = 2535 OR UVIS_MR_DIAGNOSIS.DIAGNOSIS_ID = 214 OR UVIS_MR_DIAGNOSIS.DIAGNOSIS_ID = 213 OR UVIS_MR_DIAGNOSIS.DIAGNOSIS_ID = 211 OR UVIS_MR_DIAGNOSIS.DIAGNOSIS_ID = 2537)
AND UVIS_PATIENT.SPECIES_ID = 6 AND UVIS_MR_REQUEST.EPISODE_ID = UVIS_MR_EPISODE.EPISODE_ID AND UVIS_MR_REQUEST_ITEMS.REQUEST_ID = UVIS_MR_REQUEST.REQUEST_ID AND UVIS_MR_VITAL_SIGNS.EPISODE_ID = UVIS_MR_EPISODE.EPISODE_ID AND UVIS_PRODUCT.PRODUCT_LINE_ID = UVIS_MR_REQUEST_ITEMS.PRODUCT_LINE_ID
AND UVIS_PRODUCT.PRODUCT_SEQ_ID = UVIS_MR_REQUEST_ITEMS.PRODUCT_SEQ_ID AND UVIS_MR_REQUEST_ITEMS.PRODUCT_LINE_ID = 800 AND UVIS_MR_REQUEST_ITEMS.PRODUCT_SEQ_ID = 700 AND UVIS_CL_REQUEST.HOSP_REQUEST_ID = UVIS_MR_REQUEST.REQUEST_ID AND UVIS_CL_RESULT.REQUEST_ID = UVIS_CL_REQUEST.REQUEST_ID
AND UVIS_MR_VITAL_SIGNS.VITALS_DATETIME = (SELECT MIN(UVIS_MR_VITAL_SIGNS.VITALS_DATETIME) FROM UVIS_MR_VITAL_SIGNS WHERE UVIS_MR_VITAL_SIGNS.EPISODE_ID = UVIS_MR_EPISODE.EPISODE_ID) AND UVIS_CL_RESULT.RTEST_ID = UVIS_CL_TEST_M.TEST_ID;