--These queries find all instances of a BANA test being done on Urine and Skin specimens respectively.  Restricts the search to specimens coming from the VMTH.
--URINE only
SELECT acc.ACCESSION_NO, entry.TEST_RESULT_ID, entry.TEST_CODE, entry.RESULT_NAME, entry.RESULT_VALUE, results.RECORDED_DATE, acc.CLIENT_ID 

FROM UVIS_DL_TEST_RESULTS_ENTRY entry, UVIS_DL_TEST_RESULTS_M results, UVIS_DL_ACCESSIONS acc 

WHERE entry.TEST_CODE = 'BANA' AND entry.RESULT_NAME = 'SPECIMEN ID' AND (entry.RESULT_VALUE LIKE '%URINE%' OR entry.RESULT_VALUE LIKE '%Urine%' OR entry.RESULT_VALUE LIKE '%urine%') AND entry.ACCESSION_ID = results.ACCESSION_ID AND entry.ACCESSION_ID = acc.ACCESSION_ID AND acc.CLIENT_ID = '18' AND results.RECORDED_DATE BETWEEN '1-JAN-14' AND '1-JAN-15' AND entry.TEST_CODE = results.TEST_CODE ORDER BY ACCESSION_NO;
--Skin only
SELECT acc.ACCESSION_NO, entry.TEST_RESULT_ID, entry.TEST_CODE, entry.RESULT_NAME, entry.RESULT_VALUE, results.RECORDED_DATE, acc.CLIENT_ID 

FROM UVIS_DL_TEST_RESULTS_ENTRY entry, UVIS_DL_TEST_RESULTS_M results, UVIS_DL_ACCESSIONS acc 

WHERE entry.TEST_CODE = 'BANA' AND entry.RESULT_NAME = 'SPECIMEN ID' AND (entry.RESULT_VALUE LIKE '%SKIN%' OR entry.RESULT_VALUE LIKE '%Skin%' OR entry.RESULT_VALUE LIKE '%skin%') AND entry.ACCESSION_ID = results.ACCESSION_ID AND entry.ACCESSION_ID = acc.ACCESSION_ID AND acc.CLIENT_ID = '18' AND results.RECORDED_DATE BETWEEN '1-JAN-14' AND '1-JAN-15' AND entry.TEST_CODE = results.TEST_CODE ORDER BY ACCESSION_NO;