--Returns a list all instances that a product with a line number between 200 and 299 (central supply products) was used during a given time frame.
SELECT dtl.ORDER_ID, dtl.PRODUCT_LINE_ID, dtl.PRODUCT_SEQ_ID, prod.LONG_DESCRIPTION, dtl.ORDER_ITEM_DATETIME, dtl.BASE_PRICE, dtl.ORDER_ITEM_QTY, dtl.ITEM_TOTAL_AMT, dtl.SERVICE_ID, serv.SERVICE_NAME

FROM UVIS_ORDER_DTL dtl, UVIS_PRODUCT prod, UVIS_SERVICE_AREA_M serv

WHERE dtl.ORDER_ITEM_DATETIME BETWEEN '1-APR-15' AND '1-MAY-15' AND dtl.PRODUCT_LINE_ID BETWEEN '200' AND '299' AND dtl.PRODUCT_LINE_ID = prod.PRODUCT_LINE_ID AND dtl.PRODUCT_SEQ_ID = prod.PRODUCT_SEQ_ID AND dtl.ORDER_ITEM_STATUS = 'FN' AND dtl.SERVICE_ID = serv.SERVICE_ID;


--Finds 2-135 product orders during a given time frame, and returns the name of the employee associated with that bill line.
SELECT ORDER_ID, ORDER_ITEM_DATETIME, SERVICE_NAME, ORDER_ITEM_COMMENT, EMP_ID, FIRST_NAME, LAST_NAME FROM 

(SELECT dtl.ORDER_ID, dtl.ORDER_ITEM_SEQ_ID, dtl.ORDER_ID_SUFFIX, dtl.ORDER_ITEM_DATETIME, serv.SERVICE_NAME, dtl.ORDER_ITEM_COMMENT FROM UVIS_ORDER_DTL dtl, UVIS_SERVICE_AREA_M serv WHERE dtl.PRODUCT_LINE_ID = '2' AND dtl.PRODUCT_SEQ_ID = '135' AND dtl.ORDER_ITEM_DATETIME BETWEEN '1-MAY-15' AND '1-JUN-15' AND dtl.ORDER_ITEM_STATUS = 'FN' AND dtl.SERVICE_ID = serv.SERVICE_ID)

LEFT JOIN (SELECT dtl.ORDER_ID AS ORDER_ID2, dtl.ORDER_ID_SUFFIX AS ORDER_ID_SUFFIX2, dtl.ORDER_ITEM_SEQ_ID AS ORDER_ITEM_SEQ_ID2, dtl.EMP_ID FROM UVIS_ORDER_DTL dtl) ON ORDER_ID = ORDER_ID2 AND ORDER_ITEM_SEQ_ID = ORDER_ITEM_SEQ_ID2 AND ORDER_ID_SUFFIX = ORDER_ID_SUFFIX2

LEFT JOIN (SELECT EMP_ID AS EMP_ID2, FIRST_NAME, LAST_NAME FROM UVIS_EMPLOYEE) ON EMP_ID = EMP_ID2;