--Finds orders where the dummy service/section was listed on the order header from a given time frame and returns info on the discharge dvm for each order.
SELECT * FROM (SELECT dtl.ORDER_ID, dtl.ORDER_ID_SUFFIX, dtl.PRODUCT_LINE_ID, dtl.PRODUCT_SEQ_ID, prod.SHORT_DESCRIPTION, dtl.ITEM_TOTAL_AMT, serv.SERVICE_NAME, section.SECTION_NAME, ep.DISCHARGE_DVM, dtl.ORDER_DATETIME, hdr.DISCHARGE_DATE, patient.PATIENT_NAME, hdr.PATIENT_ID, client.FIRST_NAME, client.LAST_NAME, hdr.CLIENT_ID

FROM UVIS_ORDER_HDR hdr, UVIS_ORDER_DTL dtl, UVIS_PATIENT patient, UVIS_MR_EPISODE ep, UVIS_CLIENT client, UVIS_SERVICE_AREA_M serv, UVIS_SERVICE_AREA_SECTIONS section, UVIS_PRODUCT prod

WHERE dtl.ORDER_DATETIME BETWEEN '1-JUL-12' AND sysdate AND dtl.SERVICE_ID = '193' AND dtl.SECTION_ID = '1713' AND dtl.ORDER_ID = hdr.ORDER_ID AND dtl.ORDER_ID_SUFFIX = hdr.ORDER_ID_SUFFIX AND hdr.ORDER_ID = ep.EPISODE_ID AND hdr.PATIENT_ID = patient.PATIENT_ID AND hdr.CLIENT_ID = client.CLIENT_ID AND patient.ACTIVE_YN = 'Y' AND dtl.ORDER_ITEM_STATUS = 'FN' AND hdr.ADMITTING_SERVICE_ID = serv.SERVICE_ID AND hdr.ADMITTING_SERVICE_ID = section.SERVICE_ID AND hdr.ADMITTING_SECTION_ID = section.SECTION_ID AND dtl.PRODUCT_LINE_ID = prod.PRODUCT_LINE_ID AND dtl.PRODUCT_SEQ_ID = prod.PRODUCT_SEQ_ID)

INNER JOIN (SELECT emp.EMP_ID, emp.FIRST_NAME, emp.LAST_NAME, serv.SERVICE_NAME AS DISCHARGE_SERVICE, section.SECTION_NAME AS DISCHARGE_SECTION

FROM UVIS_EMPLOYEE emp, UVIS_SERVICE_AREA_M serv, UVIS_SERVICE_AREA_SECTIONS section

WHERE emp.DVM_YN = 'Y' AND emp.SERVICE_ID = serv.SERVICE_ID AND emp.SERVICE_ID = section.SERVICE_ID AND emp.SECTION_ID = section.SECTION_ID)

ON EMP_ID = DISCHARGE_DVM;