--This query counts accessions with a Standard Diagnosis result during a given time frame
SELECT COUNT(DISTINCT UVIS_DL_TEST_RESULTS_ENTRY.ACCESSION_ID) 

FROM UVIS_DL_TEST_RESULTS_ENTRY, UVIS_DL_ACCESSIONS 

WHERE UVIS_DL_ACCESSIONS.ACCESSION_ID = UVIS_DL_TEST_RESULTS_ENTRY.ACCESSION_ID AND UVIS_DL_TEST_RESULTS_ENTRY.RESULT_NAME = 'STANDARD DIAG' AND UVIS_DL_ACCESSIONS.RECEIVED_DATE < to_date('2-MAY-14','DD-MON-YY') AND UVIS_DL_ACCESSIONS.RECEIVED_DATE > to_date('1-MAY-13','DD-MON-YY');

--This query returns the RESULT_VALUE_2ND field of accessions with a Standard Diagnosis result during a given time frame as long as the RESULT_VALUE_2ND field is not null
SELECT UVIS_DL_TEST_RESULTS_ENTRY.ACCESSION_ID, UVIS_DL_TEST_RESULTS_ENTRY.RESULT_VALUE_2ND 

FROM UVIS_DL_ACCESSIONS, UVIS_DL_TEST_RESULTS_ENTRY 

WHERE UVIS_DL_ACCESSIONS.ACCESSION_ID = UVIS_DL_TEST_RESULTS_ENTRY.ACCESSION_ID AND UVIS_DL_TEST_RESULTS_ENTRY.RESULT_NAME = 'STANDARD DIAG' AND UVIS_DL_ACCESSIONS.RECEIVED_DATE < to_date('2-MAY-14','DD-MON-YY') AND UVIS_DL_ACCESSIONS.RECEIVED_DATE > to_date('1-MAY-13','DD-MON-YY') AND UVIS_DL_TEST_RESULTS_ENTRY.RESULT_VALUE_2ND IS NOT null;

--This query returns distinct RESULT_VALUE_2ND values of Standard Diagnosis results over a given timeframe
SELECT DISTINCT UVIS_DL_TEST_RESULTS_ENTRY.RESULT_VALUE_2ND 

FROM UVIS_DL_ACCESSIONS, UVIS_DL_TEST_RESULTS_ENTRY 

WHERE UVIS_DL_ACCESSIONS.ACCESSION_ID = UVIS_DL_TEST_RESULTS_ENTRY.ACCESSION_ID AND UVIS_DL_TEST_RESULTS_ENTRY.RESULT_NAME = 'STANDARD DIAG' AND UVIS_DL_ACCESSIONS.RECEIVED_DATE < to_date('1-JAN-13','DD-MON-YY') AND UVIS_DL_ACCESSIONS.RECEIVED_DATE > to_date('1-JAN-12','DD-MON-YY') AND UVIS_DL_TEST_RESULTS_ENTRY.RESULT_VALUE_2ND IS NOT null;

--This counts how many times 'BODY AS A WHOLE' showed up in the RESULT_VALUE_2ND column of a Standard Diagnosis of accessions with species ID 6 during a given timeframe.
SELECT COUNT(UVIS_DL_TEST_RESULTS_ENTRY.TEST_RESULT_ID) 

FROM UVIS_DL_ACCESSION_ANIMAL_X, UVIS_DL_ACCESSIONS, UVIS_DL_TEST_RESULTS_ENTRY 

WHERE UVIS_DL_ACCESSIONS.ACCESSION_ID = UVIS_DL_ACCESSION_ANIMAL_X.ACCESSION_ID AND UVIS_DL_ACCESSIONS.ACCESSION_ID = UVIS_DL_TEST_RESULTS_ENTRY.ACCESSION_ID AND UVIS_DL_TEST_RESULTS_ENTRY.RESULT_NAME = 'STANDARD DIAG' AND UVIS_DL_ACCESSIONS.RECEIVED_DATE < to_date('1-JAN-13','DD-MON-YY') AND UVIS_DL_ACCESSIONS.RECEIVED_DATE > to_date('1-JAN-12','DD-MON-YY') AND UVIS_DL_TEST_RESULTS_ENTRY.RESULT_VALUE_2ND = 'BODY AS A WHOLE' AND UVIS_DL_ACCESSION_ANIMAL_X.SPECIES_ID = 6;