--The individual queries listed below find instances of the designated product codes being requested and making it to FN status over a given timeframe
--and returns the amount charged for that product, the total amount charged for the order it was located on, and the accession number of the accession
--that the request was fulfilled on.

**********************WORKS FOR 920-85********************************************

SELECT UVIS_ORDER_DTL.ORDER_ID, UVIS_MR_REQUEST.ITEM_DESCRIPTION, UVIS_ORDER_DTL.ITEM_TOTAL_AMT, SUM(eod.CHARGE_AMT), acc.ACCESSION_NO
 
FROM UVIS_DL_REQUEST_ACCESSION_X@uvisdlab dlr, UVIS_DL_EOD_CHARGES@uvisdlab eod, UVIS_ORDER_DTL, UVIS_MR_REQUEST, UVIS_DL_ACCESSIONS@uvisdlab acc
 
WHERE UVIS_ORDER_DTL.PRODUCT_LINE_ID = 920 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 85
AND UVIS_ORDER_DTL.ORDER_ID = UVIS_MR_REQUEST.EPISODE_ID
AND UVIS_MR_REQUEST.REQUEST_ID = dlr.REQUEST_ID_SOURCE AND dlr.ACCESSION_ID = eod.ACCESSION_ID AND eod.PRODUCT_LINE_ID = 920
AND UVIS_ORDER_DTL.ORDER_ITEM_STATUS = 'FN' AND dlr.REQUEST_STATUS = 'ACCEPTED' AND UVIS_ORDER_DTL.ORDER_DATETIME BETWEEN '1-JUN-13' AND '1-JUL-14'
AND eod.ACCESSION_ID = acc.ACCESSION_ID

GROUP BY UVIS_ORDER_DTL.ORDER_ID, UVIS_ORDER_DTL.ITEM_TOTAL_AMT, UVIS_MR_REQUEST.ITEM_DESCRIPTION, acc.ACCESSION_NO;


************************WORKS FOR 920-86*********************************************

SELECT UVIS_ORDER_DTL.ORDER_ID, UVIS_MR_REQUEST.ITEM_DESCRIPTION, UVIS_ORDER_DTL.ITEM_TOTAL_AMT, SUM(eod.CHARGE_AMT), acc.ACCESSION_NO
 
FROM UVIS_DL_REQUEST_ACCESSION_X@uvisdlab dlr, UVIS_DL_EOD_CHARGES@uvisdlab eod, UVIS_ORDER_DTL, UVIS_MR_REQUEST, UVIS_DL_ACCESSIONS@uvisdlab acc
 
WHERE UVIS_ORDER_DTL.PRODUCT_LINE_ID = 920 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 86
AND UVIS_ORDER_DTL.ORDER_ID = UVIS_MR_REQUEST.EPISODE_ID
AND UVIS_MR_REQUEST.REQUEST_ID = dlr.REQUEST_ID_SOURCE AND dlr.ACCESSION_ID = eod.ACCESSION_ID AND eod.PRODUCT_LINE_ID = 920
AND UVIS_ORDER_DTL.ORDER_ITEM_STATUS = 'FN' AND dlr.REQUEST_STATUS = 'ACCEPTED' AND UVIS_ORDER_DTL.ORDER_DATETIME BETWEEN '1-JUN-13' AND '1-JUL-14'
AND eod.ACCESSION_ID = acc.ACCESSION_ID

GROUP BY UVIS_ORDER_DTL.ORDER_ID, UVIS_ORDER_DTL.ITEM_TOTAL_AMT, UVIS_MR_REQUEST.ITEM_DESCRIPTION, acc.ACCESSION_NO;

**************************WORKS FOR 920-87********************************************

SELECT UVIS_ORDER_DTL.ORDER_ID, UVIS_MR_REQUEST.ITEM_DESCRIPTION, UVIS_ORDER_DTL.ITEM_TOTAL_AMT, SUM(eod.CHARGE_AMT), acc.ACCESSION_NO
 
FROM UVIS_DL_REQUEST_ACCESSION_X@uvisdlab dlr, UVIS_DL_EOD_CHARGES@uvisdlab eod, UVIS_ORDER_DTL, UVIS_MR_REQUEST, UVIS_DL_ACCESSIONS@uvisdlab acc
 
WHERE UVIS_ORDER_DTL.PRODUCT_LINE_ID = 920 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 87
AND UVIS_ORDER_DTL.ORDER_ID = UVIS_MR_REQUEST.EPISODE_ID
AND UVIS_MR_REQUEST.REQUEST_ID = dlr.REQUEST_ID_SOURCE AND dlr.ACCESSION_ID = eod.ACCESSION_ID AND eod.PRODUCT_LINE_ID = 920
AND UVIS_ORDER_DTL.ORDER_ITEM_STATUS = 'FN' AND dlr.REQUEST_STATUS = 'ACCEPTED' AND UVIS_ORDER_DTL.ORDER_DATETIME BETWEEN '1-JUN-13' AND '1-JUL-14'
AND eod.ACCESSION_ID = acc.ACCESSION_ID

GROUP BY UVIS_ORDER_DTL.ORDER_ID, UVIS_ORDER_DTL.ITEM_TOTAL_AMT, UVIS_MR_REQUEST.ITEM_DESCRIPTION, acc.ACCESSION_NO;

***************************WORKS FOR 930-650********************************************

SELECT UVIS_ORDER_DTL.ORDER_ID, UVIS_MR_REQUEST.ITEM_DESCRIPTION, UVIS_ORDER_DTL.ITEM_TOTAL_AMT, SUM(eod.CHARGE_AMT), acc.ACCESSION_NO
 
FROM UVIS_DL_REQUEST_ACCESSION_X@uvisdlab dlr, UVIS_DL_EOD_CHARGES@uvisdlab eod, UVIS_ORDER_DTL, UVIS_MR_REQUEST, UVIS_DL_ACCESSIONS@uvisdlab acc
 
WHERE UVIS_ORDER_DTL.PRODUCT_LINE_ID = 930 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 650
AND UVIS_ORDER_DTL.ORDER_ID = UVIS_MR_REQUEST.EPISODE_ID
AND UVIS_MR_REQUEST.REQUEST_ID = dlr.REQUEST_ID_SOURCE AND dlr.ACCESSION_ID = eod.ACCESSION_ID AND eod.PRODUCT_LINE_ID = 930
AND UVIS_ORDER_DTL.ORDER_ITEM_STATUS = 'FN' AND dlr.REQUEST_STATUS = 'ACCEPTED' AND UVIS_ORDER_DTL.ORDER_DATETIME BETWEEN '1-JUN-13' AND '1-JUL-14'
AND eod.ACCESSION_ID = acc.ACCESSION_ID

GROUP BY UVIS_ORDER_DTL.ORDER_ID, UVIS_ORDER_DTL.ITEM_TOTAL_AMT, UVIS_MR_REQUEST.ITEM_DESCRIPTION, acc.ACCESSION_NO;

*********************************MODIFIED 930-650 SEARCH******************************

SELECT UVIS_ORDER_DTL.ORDER_ID AS o_id, UVIS_ORDER_DTL.ORDER_ITEM_SEQ_ID AS seq_id, UVIS_PRODUCT.BILLING_DESCRIPTION AS description, UVIS_ORDER_DTL.ITEM_TOTAL_AMT AS hosp_amt, SUM(eod.CHARGE_AMT) AS lab_amt, acc.ACCESSION_NO AS accession_no
 
FROM UVIS_DL_REQUEST_ACCESSION_X@uvisdlab dlr, UVIS_DL_EOD_CHARGES@uvisdlab eod, UVIS_ORDER_DTL, UVIS_MR_REQUEST, UVIS_DL_ACCESSIONS@uvisdlab acc, UVIS_MR_REQUEST_ITEMS, UVIS_PRODUCT
 
WHERE UVIS_MR_REQUEST_ITEMS.PRODUCT_LINE_ID = 930 AND UVIS_PRODUCT.PRODUCT_LINE_ID = UVIS_MR_REQUEST_ITEMS.PRODUCT_LINE_ID AND UVIS_PRODUCT.PRODUCT_SEQ_ID = UVIS_MR_REQUEST_ITEMS.PRODUCT_SEQ_ID
AND UVIS_ORDER_DTL.ORDER_ID = UVIS_MR_REQUEST.EPISODE_ID AND UVIS_ORDER_DTL.PRODUCT_LINE_ID = UVIS_MR_REQUEST_ITEMS.PRODUCT_LINE_ID AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = UVIS_MR_REQUEST_ITEMS.PRODUCT_SEQ_ID
AND UVIS_MR_REQUEST.REQUEST_ID = dlr.REQUEST_ID_SOURCE AND dlr.ACCESSION_ID = eod.ACCESSION_ID AND eod.PRODUCT_LINE_ID = 930
AND UVIS_MR_REQUEST.STATUS = 'COMPLETE' AND dlr.REQUEST_STATUS = 'ACCEPTED' AND UVIS_ORDER_DTL.ORDER_DATETIME BETWEEN '1-JUN-13' AND '1-JUL-14'
AND eod.ACCESSION_ID = acc.ACCESSION_ID

GROUP BY UVIS_ORDER_DTL.ORDER_ID, UVIS_ORDER_DTL.ORDER_ITEM_SEQ_ID, UVIS_ORDER_DTL.ITEM_TOTAL_AMT, UVIS_PRODUCT.BILLING_DESCRIPTION, acc.ACCESSION_NO;


--This query finds 930 line number product codes other than 930-650 and returns the amount charged for the code on the hospital side as well as the lab side and the accession number 
--on the lab side.
SELECT o_id, seq_id, description, hosp_amt, lab_amt, accession_no FROM (

SELECT UVIS_ORDER_DTL.ORDER_ID AS o_id, UVIS_ORDER_DTL.ORDER_ITEM_SEQ_ID AS seq_id, UVIS_PRODUCT.BILLING_DESCRIPTION AS description, UVIS_ORDER_DTL.ITEM_TOTAL_AMT AS hosp_amt, SUM(DISTINCT eod.CHARGE_AMT) AS lab_amt, acc.ACCESSION_NO AS accession_no, eod.SPECIMEN_ID AS spec_ID
 
FROM UVIS_DL_REQUEST_ACCESSION_X@uvisdlab dlr, UVIS_DL_EOD_CHARGES@uvisdlab eod, UVIS_ORDER_DTL, UVIS_MR_REQUEST, UVIS_DL_ACCESSIONS@uvisdlab acc, UVIS_MR_REQUEST_ITEMS, UVIS_PRODUCT
 
WHERE UVIS_MR_REQUEST_ITEMS.PRODUCT_LINE_ID = 930 AND UVIS_PRODUCT.PRODUCT_LINE_ID = UVIS_MR_REQUEST_ITEMS.PRODUCT_LINE_ID AND UVIS_PRODUCT.PRODUCT_SEQ_ID = UVIS_MR_REQUEST_ITEMS.PRODUCT_SEQ_ID
AND UVIS_ORDER_DTL.ORDER_ID = UVIS_MR_REQUEST.EPISODE_ID AND UVIS_ORDER_DTL.PRODUCT_LINE_ID = UVIS_MR_REQUEST_ITEMS.PRODUCT_LINE_ID AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = UVIS_MR_REQUEST_ITEMS.PRODUCT_SEQ_ID
AND UVIS_MR_REQUEST.REQUEST_ID = dlr.REQUEST_ID_SOURCE AND dlr.ACCESSION_ID = eod.ACCESSION_ID AND eod.PRODUCT_LINE_ID = 930
AND UVIS_MR_REQUEST.STATUS = 'COMPLETE' AND dlr.REQUEST_STATUS = 'ACCEPTED' AND UVIS_ORDER_DTL.ORDER_DATETIME BETWEEN '1-JUN-13' AND '1-JUL-14'
AND eod.ACCESSION_ID = acc.ACCESSION_ID AND eod.PRODUCT_SEQ_ID = UVIS_MR_REQUEST_ITEMS.PRODUCT_SEQ_ID

GROUP BY UVIS_ORDER_DTL.ORDER_ID, UVIS_ORDER_DTL.ORDER_ITEM_SEQ_ID, UVIS_ORDER_DTL.ITEM_TOTAL_AMT, UVIS_PRODUCT.BILLING_DESCRIPTION, acc.ACCESSION_NO, eod.SPECIMEN_ID) LEFT OUTER JOIN (

SELECT UVIS_ORDER_DTL.ORDER_ID AS o_id1, UVIS_MR_REQUEST.ITEM_DESCRIPTION AS desc1, UVIS_ORDER_DTL.ITEM_TOTAL_AMT AS hosp_amt1, SUM(eod.CHARGE_AMT) AS lab_amt1, acc.ACCESSION_NO AS acc_no1
 
FROM UVIS_DL_REQUEST_ACCESSION_X@uvisdlab dlr, UVIS_DL_EOD_CHARGES@uvisdlab eod, UVIS_ORDER_DTL, UVIS_MR_REQUEST, UVIS_DL_ACCESSIONS@uvisdlab acc
 
WHERE UVIS_ORDER_DTL.PRODUCT_LINE_ID = 930 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 650
AND UVIS_ORDER_DTL.ORDER_ID = UVIS_MR_REQUEST.EPISODE_ID
AND UVIS_MR_REQUEST.REQUEST_ID = dlr.REQUEST_ID_SOURCE AND dlr.ACCESSION_ID = eod.ACCESSION_ID AND eod.PRODUCT_LINE_ID = 930
AND UVIS_ORDER_DTL.ORDER_ITEM_STATUS = 'FN' AND dlr.REQUEST_STATUS = 'ACCEPTED' AND UVIS_ORDER_DTL.ORDER_DATETIME BETWEEN '1-JUN-13' AND '1-JUL-14'
AND eod.ACCESSION_ID = acc.ACCESSION_ID

GROUP BY UVIS_ORDER_DTL.ORDER_ID, UVIS_ORDER_DTL.ITEM_TOTAL_AMT, UVIS_MR_REQUEST.ITEM_DESCRIPTION, acc.ACCESSION_NO) ON o_id = o_id1 WHERE o_id1 is NULL;

---------------------------------------BREAK------------------------------------------------------------

--Necropsy and Disposal/Cremation Codes
--This query finds instances where necropsy and cremation codes were used and returns the amount charged for them.
SELECT o_id, UVIS_ORDER_DTL.ORDER_ITEM_SEQ_ID, UVIS_ORDER_DTL.ITEM_TOTAL_AMT FROM (SELECT UVIS_ORDER_DTL.ORDER_ID AS o_id, UVIS_ORDER_DTL.ITEM_TOTAL_AMT AS amt 

FROM UVIS_ORDER_DTL WHERE UVIS_ORDER_DTL.PRODUCT_LINE_ID = 900 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 30 AND UVIS_ORDER_DTL.ORDER_DATETIME BETWEEN '1-JUN-13' AND '1-JUL-14'), UVIS_ORDER_DTL 

WHERE ((UVIS_ORDER_DTL.PRODUCT_LINE_ID = 900 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 20) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 900 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 2810) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 900 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 14) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 905 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 2400) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 490 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 600) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 590 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 100) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 670 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 500) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 490 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 500) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 490 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 520) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 490 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 521) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 490 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 522) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 490 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 540) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 490 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 560) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 490 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 580)) AND UVIS_ORDER_DTL.ORDER_ID = o_id AND UVIS_ORDER_DTL.ORDER_ITEM_STATUS = 'FN' AND UVIS_ORDER_DTL.ITEM_TOTAL_AMT > 0;

--Just Necropsy Codes
--This does the same as above but just for necropsy codes.
SELECT o_id1 FROM (SELECT UVIS_ORDER_DTL.ORDER_ID AS o_id1, UVIS_ORDER_DTL.ITEM_TOTAL_AMT AS amt FROM UVIS_ORDER_DTL WHERE UVIS_ORDER_DTL.PRODUCT_LINE_ID = 900 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 30 AND UVIS_ORDER_DTL.ORDER_DATETIME BETWEEN '1-JUN-13' AND '1-JUL-14') LEFT OUTER JOIN (SELECT o_id2, UVIS_ORDER_DTL.ITEM_TOTAL_AMT, UVIS_ORDER_DTL.ORDER_ITEM_SEQ_ID FROM (SELECT UVIS_ORDER_DTL.ORDER_ID AS o_id2, UVIS_ORDER_DTL.ITEM_TOTAL_AMT AS amt 

FROM UVIS_ORDER_DTL WHERE UVIS_ORDER_DTL.PRODUCT_LINE_ID = 900 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 30 AND UVIS_ORDER_DTL.ORDER_DATETIME BETWEEN '1-JUN-13' AND '1-JUL-14'), UVIS_ORDER_DTL 

WHERE ((UVIS_ORDER_DTL.PRODUCT_LINE_ID = 900 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 20) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 900 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 2810) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 900 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 14) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 905 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 2400) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 490 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 600) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 590 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 100) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 670 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 500) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 490 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 500) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 490 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 520) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 490 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 521) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 490 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 522) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 490 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 540) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 490 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 560) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 490 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 580)) AND UVIS_ORDER_DTL.ORDER_ID = o_id2) ON o_id1 = o_id2 WHERE o_id2 is NULL;

--Combining with Lab (Orders with disposal/cremation charges)
--This does the same as the first after the break but also shows what was charged on the lab side.
SELECT o_id, UVIS_ORDER_DTL.ORDER_ITEM_SEQ_ID, UVIS_MR_REQUEST.ITEM_DESCRIPTION, UVIS_ORDER_DTL.ITEM_TOTAL_AMT, SUM(DISTINCT eod.CHARGE_AMT), acc.ACCESSION_NO FROM (SELECT UVIS_ORDER_DTL.ORDER_ID AS o_id, UVIS_ORDER_DTL.ITEM_TOTAL_AMT AS amt 

FROM UVIS_ORDER_DTL WHERE UVIS_ORDER_DTL.PRODUCT_LINE_ID = 900 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 30 AND UVIS_ORDER_DTL.ORDER_DATETIME BETWEEN '1-JUN-13' AND '1-JUL-14'), UVIS_DL_REQUEST_ACCESSION_X@uvisdlab dlr, UVIS_DL_EOD_CHARGES@uvisdlab eod, UVIS_ORDER_DTL, UVIS_MR_REQUEST, UVIS_DL_ACCESSIONS@uvisdlab acc, UVIS_MR_REQUEST_ITEMS 

WHERE ((UVIS_ORDER_DTL.PRODUCT_LINE_ID = 900 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 20) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 900 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 2810) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 900 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 14) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 905 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 2400) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 490 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 600) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 590 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 100) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 670 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 500)) AND UVIS_ORDER_DTL.ORDER_ID = o_id AND UVIS_ORDER_DTL.ORDER_ITEM_STATUS = 'FN' AND UVIS_ORDER_DTL.ITEM_TOTAL_AMT > 0

AND UVIS_ORDER_DTL.ORDER_ID = UVIS_MR_REQUEST.EPISODE_ID AND UVIS_MR_REQUEST.REQUEST_ID = UVIS_MR_REQUEST_ITEMS.REQUEST_ID AND UVIS_MR_REQUEST_ITEMS.PRODUCT_LINE_ID = 900 AND UVIS_MR_REQUEST_ITEMS.PRODUCT_SEQ_ID = 30
AND UVIS_MR_REQUEST.REQUEST_ID = dlr.REQUEST_ID_SOURCE AND dlr.ACCESSION_ID = eod.ACCESSION_ID AND dlr.REQUEST_STATUS = 'ACCEPTED' AND eod.ACCESSION_ID = acc.ACCESSION_ID

GROUP BY o_id, UVIS_ORDER_DTL.ORDER_ITEM_SEQ_ID, UVIS_MR_REQUEST.ITEM_DESCRIPTION, UVIS_ORDER_DTL.ITEM_TOTAL_AMT, acc.ACCESSION_NO;

--Combining with Lab (Orders with no disposal/cremation charges)
--This is the same as the second query after the break but shows what was charged on the lab side.
SELECT o_id1, seq_id, item_desc, hosp_amt, lab_amt, acc_no FROM (SELECT UVIS_ORDER_DTL.ORDER_ID AS o_id1, UVIS_ORDER_DTL.ORDER_ITEM_SEQ_ID AS seq_id, UVIS_MR_REQUEST.ITEM_DESCRIPTION AS item_desc, UVIS_ORDER_DTL.ITEM_TOTAL_AMT AS hosp_amt, SUM(eod.CHARGE_AMT) AS lab_amt, acc.ACCESSION_NO AS acc_no FROM UVIS_DL_REQUEST_ACCESSION_X@uvisdlab dlr, UVIS_DL_EOD_CHARGES@uvisdlab eod, UVIS_ORDER_DTL, UVIS_MR_REQUEST, UVIS_DL_ACCESSIONS@uvisdlab acc, UVIS_MR_REQUEST_ITEMS 

WHERE UVIS_ORDER_DTL.PRODUCT_LINE_ID = 900 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 30
AND UVIS_ORDER_DTL.ORDER_ITEM_STATUS = 'FN' AND UVIS_ORDER_DTL.ORDER_DATETIME BETWEEN '1-JUN-13' AND '1-JUL-14'
AND UVIS_ORDER_DTL.ORDER_ID = UVIS_MR_REQUEST.EPISODE_ID AND UVIS_MR_REQUEST.REQUEST_ID = UVIS_MR_REQUEST_ITEMS.REQUEST_ID AND UVIS_MR_REQUEST_ITEMS.PRODUCT_LINE_ID = 900 AND UVIS_MR_REQUEST_ITEMS.PRODUCT_SEQ_ID = 30
AND UVIS_MR_REQUEST.REQUEST_ID = dlr.REQUEST_ID_SOURCE AND dlr.ACCESSION_ID = eod.ACCESSION_ID AND dlr.REQUEST_STATUS = 'ACCEPTED' AND eod.ACCESSION_ID = acc.ACCESSION_ID

GROUP BY UVIS_ORDER_DTL.ORDER_ID, UVIS_ORDER_DTL.ORDER_ITEM_SEQ_ID, UVIS_MR_REQUEST.ITEM_DESCRIPTION, UVIS_ORDER_DTL.ITEM_TOTAL_AMT, acc.ACCESSION_NO) LEFT OUTER JOIN (SELECT o_id2, UVIS_ORDER_DTL.ITEM_TOTAL_AMT, UVIS_ORDER_DTL.ORDER_ITEM_SEQ_ID FROM (SELECT UVIS_ORDER_DTL.ORDER_ID AS o_id2, UVIS_ORDER_DTL.ITEM_TOTAL_AMT AS amt 

FROM UVIS_ORDER_DTL WHERE UVIS_ORDER_DTL.PRODUCT_LINE_ID = 900 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 30 AND UVIS_ORDER_DTL.ORDER_DATETIME BETWEEN '1-JUN-13' AND '1-JUL-14'), UVIS_ORDER_DTL 

WHERE ((UVIS_ORDER_DTL.PRODUCT_LINE_ID = 900 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 20) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 900 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 2810) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 900 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 14) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 905 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 2400) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 490 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 600) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 590 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 100) OR (UVIS_ORDER_DTL.PRODUCT_LINE_ID = 670 AND UVIS_ORDER_DTL.PRODUCT_SEQ_ID = 500)) AND UVIS_ORDER_DTL.ORDER_ID = o_id2) ON o_id1 = o_id2 WHERE o_id2 is NULL;