--This finds product codes with a line number between 100 and 199 with a listed inventory area of 'PHARMACY'
SELECT prod.PRODUCT_LINE_ID, prod.PRODUCT_SEQ_ID, prod.SHORT_DESCRIPTION, inv.INVENTORY_AREA, inv.BIN_LOCATION, prod.PRODUCT_CATEGORY 
FROM UVIS_PRODUCT prod, UVIS_INVENTORY inv 
WHERE prod.PRODUCT_LINE_ID BETWEEN 100 AND 199 AND prod.PRODUCT_LINE_ID = inv.PRODUCT_LINE_ID AND prod.PRODUCT_SEQ_ID = inv.PRODUCT_SEQ_ID AND inv.INVENTORY_AREA = 'PHARMACY';