--Finds all pick sheets with the parent service and section listed for each
SELECT service.SERVICE_NAME, section.SECTION_NAME, title.SHEET_TYPE, title.SHEET_TITLE, category.PICK_CATEGORY, pick.PRODUCT_LINE_ID, pick.PRODUCT_SEQ_ID, prod.BILLING_DESCRIPTION

FROM UVIS_PICK_SHEET_TITLE_M title, UVIS_PICK_SHEET pick, UVIS_PICK_CATEGORY_M category, UVIS_PRODUCT prod, UVIS_SERVICE_AREA_M service, UVIS_SERVICE_AREA_SECTIONS section

WHERE title.SHEET_TITLE_ID = category.SHEET_TITLE_ID AND category.PICK_CATEGORY_ID = pick.PICK_CATEGORY_ID AND pick.PRODUCT_LINE_ID = prod.PRODUCT_LINE_ID AND pick.PRODUCT_SEQ_ID = prod.PRODUCT_SEQ_ID AND prod.ACTIVE_YN = 'Y' AND title.PARENT_SERVICE_ID = service.SERVICE_ID AND title.PARENT_SERVICE_ID = section.SERVICE_ID AND title.PARENT_SECTION_ID = section.SECTION_ID;