--Returns the number of times used and amount collected from all product codes with line numbers between 301 and 799 over a given time frame
SELECT PRODUCT_LINE_ID, PRODUCT_SEQ_ID, LONG_DESCRIPTION, TIMES_USED, TOTAL_COLLECTED 

FROM (SELECT PRODUCT_LINE_ID, PRODUCT_SEQ_ID, LONG_DESCRIPTION FROM UVIS_PRODUCT WHERE PRODUCT_LINE_ID BETWEEN '301' AND '799' AND ACTIVE_YN = 'Y') 

LEFT JOIN (SELECT PRODUCT_LINE_ID AS PRODUCT_LINE_ID2, PRODUCT_SEQ_ID AS PRODUCT_SEQ_ID2, COUNT(ORDER_ID) AS TIMES_USED, SUM(ITEM_TOTAL_AMT) AS TOTAL_COLLECTED FROM UVIS_ORDER_DTL WHERE ORDER_DATETIME BETWEEN '1-MAY-14' AND '30-APR-15' AND PRODUCT_LINE_ID BETWEEN '300' AND '799' AND ORDER_ITEM_STATUS = 'FN' GROUP BY PRODUCT_LINE_ID, PRODUCT_SEQ_ID) ON PRODUCT_LINE_ID = PRODUCT_LINE_ID2 AND PRODUCT_SEQ_ID = PRODUCT_SEQ_ID2 ORDER BY PRODUCT_LINE_ID;
