--Finds order lines where the product has the inventory area 'STERIL - PACKS' from a given time frame.
SELECT ORDER_ID, ORDER_DATETIME, PRODUCT_LINE_ID, PRODUCT_SEQ_ID, LONG_DESCRIPTION, ORDER_ITEM_QTY, BASE_PRICE, ITEM_TOTAL_AMT FROM 

(SELECT INVENTORY_AREA, PRODUCT_LINE_ID, PRODUCT_SEQ_ID FROM UVIS_INVENTORY WHERE INVENTORY_AREA = 'STERIL - PACKS')

INNER JOIN (SELECT dtl.ORDER_ID, dtl.ORDER_DATETIME, dtl.PRODUCT_LINE_ID AS PRODUCT_LINE_ID2, dtl.PRODUCT_SEQ_ID AS PRODUCT_SEQ_ID2, prod.LONG_DESCRIPTION, dtl.ORDER_ITEM_QTY, dtl.BASE_PRICE, dtl.ITEM_TOTAL_AMT FROM UVIS_ORDER_DTL dtl, UVIS_PRODUCT prod WHERE dtl.ORDER_DATETIME BETWEEN '1-JUL-15' AND '28-JUL-15' AND dtl.PRODUCT_LINE_ID = prod.PRODUCT_LINE_ID AND dtl.PRODUCT_SEQ_ID = prod.PRODUCT_SEQ_ID) ON PRODUCT_LINE_ID = PRODUCT_LINE_ID2 AND PRODUCT_SEQ_ID = PRODUCT_SEQ_ID2;