--Finds all Pharmacy product codes (line number between 100 and 199) that have not been used over a given time frame.
SELECT * FROM (SELECT prod.PRODUCT_LINE_ID AS LINE_NO1, prod.PRODUCT_SEQ_ID AS SEQ_NO1, prod.SHORT_DESCRIPTION FROM UVIS_PRODUCT prod WHERE prod.PRODUCT_LINE_ID BETWEEN '100' AND '199' AND prod.ACTIVE_YN = 'Y')

LEFT OUTER JOIN

(SELECT dtl.ORDER_ID, dtl.PRODUCT_LINE_ID AS LINE_NO2, dtl.PRODUCT_SEQ_ID AS SEQ_NO2, dtl.ORDER_DATETIME FROM UVIS_ORDER_DTL dtl WHERE dtl.ORDER_DATETIME BETWEEN '01-JAN-13' AND sysdate AND dtl.PRODUCT_LINE_ID BETWEEN '100' AND '199')

ON LINE_NO1 = LINE_NO2 AND SEQ_NO1 = SEQ_NO2 WHERE LINE_NO2 is NULL;